name: Test Project

on: [push, workflow_dispatch]

jobs:
  test-pdm:
      name: PDM install on ${{ matrix.python-version }}
      runs-on: windows-2022
      strategy:
          matrix:
              python-version: [3.11, 3.12]
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          aqtversion: '>=3.2.0'
      
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the environment
        run: pdm install -v
